import torch
import torch.nn as nn
import random
import math
import warnings
from PIL import ImageFilter, ImageOps
import numpy as np
import os
import sys
import torch.distributed as dist


def get_device() -> torch.device:
    if torch.cuda.is_available():
        return torch.device("cuda")
    if torch.backends.mps.is_available():
        return torch.device("mps")
    return torch.device("cpu")


class GaussianBlur(object):
    """
    应用高斯模糊
    """

    def __init__(self, p=0.5, radius_min=0.1, radius_max=2.0):
        self.prob = p
        self.radius_min = radius_min
        self.radius_max = radius_max

    def __call__(self, img):
        do_it = random.random() <= self.prob
        if not do_it:
            return img

        return img.filter(
            ImageFilter.GaussianBlur(
                radius=random.uniform(self.radius_min, self.radius_max)
            )
        )


class Solarization(object):
    """
    应用曝光反转/日蚀效果
    """

    def __init__(self, p):
        self.p = p

    def __call__(self, img):
        if random.random() < self.p:
            return ImageOps.solarize(img)
        else:
            return img


def get_params_group(model):
    regularized = []
    not_regularized = []
    for name, param in model.named_parameters():
        if not param.requires_grad:
            continue

        # 偏置不需要权重衰减
        if name.endswith(".bias") or len(param.shape) == 1:
            not_regularized.append(param)
        else:
            regularized.append(param)

    return [{"params": regularized}, {"params": not_regularized, "weight_decay": 0.0}]


def _no_grad_trunc_normal_(tensor, mean, std, a, b):
    # Cut & paste from PyTorch official master until it's in a few official releases - RW
    # Method based on https://people.sc.fsu.edu/~jburkardt/presentations/truncated_normal.pdf
    def norm_cdf(x):
        # Computes standard normal cumulative distribution function
        return (1.0 + math.erf(x / math.sqrt(2.0))) / 2.0

    if (mean < a - 2 * std) or (mean > b + 2 * std):
        warnings.warn(
            "mean is more than 2 std from [a, b] in nn.init.trunc_normal_. "
            "The distribution of values may be incorrect.",
            stacklevel=2,
        )

    with torch.no_grad():
        # Values are generated by using a truncated uniform distribution and
        # then using the inverse CDF for the normal distribution.
        # Get upper and lower cdf values
        l = norm_cdf((a - mean) / std)
        u = norm_cdf((b - mean) / std)

        # Uniformly fill tensor with values from [l, u], then translate to
        # [2l-1, 2u-1].
        tensor.uniform_(2 * l - 1, 2 * u - 1)

        # Use inverse cdf transform for normal distribution to get truncated
        # standard normal
        tensor.erfinv_()

        # Transform to proper mean, std
        tensor.mul_(std * math.sqrt(2.0))
        tensor.add_(mean)

        # Clamp to ensure it's in the proper range
        tensor.clamp_(min=a, max=b)
        return tensor


def trunc_normal_(tensor, mean=0.0, std=1.0, a=-2.0, b=2.0):
    # type: (Tensor, float, float, float, float) -> Tensor
    return _no_grad_trunc_normal_(tensor, mean, std, a, b)


def cosine_scheduler(
    base_value, final_value, epochs, niter_per_ep, warmup_epochs=0, start_warmup_value=0
):
    # 生成一段「逐迭代」的超参数曲线，先线性预热、再余弦退火到 final_value。
    # 总长度为 epochs * niter_per_ep（整个训练过程的迭代次数），训练时按步索引取值。
    #   base_value        : 预热结束后 / 余弦段的起始值（曲线最高点）
    #   final_value       : 曲线终点值（最低点）
    #   epochs            : 总训练轮数
    #   niter_per_ep      : 每轮迭代次数（= len(data_loader)）
    #   warmup_epochs     : 线性预热轮数（默认 0，表示不预热）
    #   start_warmup_value: 预热起点值（默认 0）

    warmup_schedule = np.array([])  # 预热段数组，先置空；无预热时保持为空
    warmup_iters = (
        warmup_epochs * niter_per_ep
    )  # 预热段的总迭代数 = 预热轮数 × 每轮迭代数

    if warmup_epochs > 0:
        # 线性预热：从 start_warmup_value 均匀升到 base_value，共 warmup_iters 个点
        warmup_schedule = np.linspace(start_warmup_value, base_value, warmup_iters)

    # 余弦段对应的迭代下标（跳过已占用的预热迭代数），形如 [0, 1, ..., T-1]
    iters = np.arange(epochs * niter_per_ep - warmup_iters)
    # 余弦退火公式：final + 0.5*(base-final)*(1 + cos(pi * t / T))
    #   t=0   -> cos(0)=1      -> 值 = base_value（起点）
    #   t=T/2 -> cos(pi/2)=0   -> 值 = 中点
    #   t=T   -> cos(pi)=-1    -> 值 = final_value（终点）
    schedule = final_value + 0.5 * (base_value - final_value) * (
        1 + np.cos(np.pi * iters / len(iters))
    )

    # 把预热段和余弦段拼成一条完整曲线（无预热时 warmup_schedule 为空，等价于只取余弦段）
    schedule = np.concatenate((warmup_schedule, schedule))
    # 校验总长度恰好等于整个训练的迭代次数
    assert len(schedule) == epochs * niter_per_ep
    return schedule


def clip_gradients(model, clip):
    norms = []
    for name, p in model.named_parameters():
        if p.grad is not None:
            param_norm = p.grad.data.norm(2)
            norms.append(param_norm.item())
            clip_coef = clip / (param_norm + 1e-6)  # 大于clip的参数，都会裁剪为clip
            if clip_coef < 1:
                p.grad.data.mul_(clip_coef)
    return norms


def cancel_gradients_last_layer(epoch, model, freeze_last_layer):
    if epoch >= freeze_last_layer:
        return
    for n, p in model.named_parameters():
        if "last_layer" in n:
            p.grad = None


def restart_from_checkpoint(ckp_path, run_variables=None, **kwargs):
    """
    Re-start from checkpoint
    """
    if not os.path.isfile(ckp_path):
        return
    print("Found checkpoint at {}".format(ckp_path))

    # open checkpoint file
    checkpoint = torch.load(ckp_path, map_location="cpu")

    # key is what to look for in the checkpoint file
    # value is the object to load
    # example: {'state_dict': model}
    for key, value in kwargs.items():
        if key in checkpoint and value is not None:
            try:
                msg = value.load_state_dict(checkpoint[key], strict=False)
                print(
                    "=> loaded '{}' from checkpoint '{}' with msg {}".format(
                        key, ckp_path, msg
                    )
                )
            except TypeError:
                try:
                    msg = value.load_state_dict(checkpoint[key])
                    print("=> loaded '{}' from checkpoint: '{}'".format(key, ckp_path))
                except ValueError:
                    print(
                        "=> failed to load '{}' from checkpoint: '{}'".format(
                            key, ckp_path
                        )
                    )
        else:
            print("=> key '{}' not found in checkpoint: '{}'".format(key, ckp_path))

    # re load variable important for the run
    if run_variables is not None:
        for var_name in run_variables:
            if var_name in checkpoint:
                run_variables[var_name] = checkpoint[var_name]


def fix_random_seeds(seed=31):
    """
    Fix random seeds.
    """
    torch.manual_seed(seed)
    torch.cuda.manual_seed_all(seed)
    np.random.seed(seed)
    random.seed(seed)


def has_batchnorms(model):
    bn_types = (nn.BatchNorm1d, nn.BatchNorm2d, nn.BatchNorm3d, nn.SyncBatchNorm)
    for name, module in model.named_modules():
        if isinstance(module, bn_types):
            return True
    return False


def is_dist_avail_and_initialized():
    if not dist.is_available():
        return False
    if not dist.is_initialized():
        return False
    return True


def get_world_size():
    if not is_dist_avail_and_initialized():
        return 1
    return dist.get_world_size()


def get_rank():
    if not is_dist_avail_and_initialized():
        return 0
    return dist.get_rank()


def is_main_process():
    return get_rank() == 0


# 保存模型到主卡
def save_on_master(*args, **kwargs):
    if is_main_process():
        torch.save(*args, **kwargs)


"""
调用 setup_for_distributed（通常是设置 utils.is_main_process() 标志，并按需关闭非主进程的打印/日志），让只有 rank==0 的主进程负责打印、保存日志、写 checkpoint 等
"""


def setup_for_distributed(is_master):
    """
    This function disables printing when not in master process
    """
    import builtins as __builtin__

    builtin_print = __builtin__.print

    def print(*args, **kwargs):
        force = kwargs.pop("force", False)
        if is_master or force:
            builtin_print(*args, **kwargs)

    __builtin__.print = print


"""
初始化分布式训练：每个 GPU 对应一个独立的进程，进程与 GPU 是一一绑定的

============================================================================
如何开启多卡训练（启动命令）
============================================================================
本函数兼容三种启动方式，进程组地址 dist_url 的处理逻辑见各命令注释。

【1. 单机多卡（最常用，推荐）】
用 torchrun（或 torch.distributed.launch）启动，它会自动注入
RANK / WORLD_SIZE / LOCAL_RANK 环境变量，dist_url 用默认 "env://" 即可。
下面命令在 1 台机器上起 N 个进程（每个 GPU 一个进程），无需手动设 dist_url：

    # N 改成你的 GPU 数量，例如 8
    torchrun --nproc_per_node=8 main_dino.py \
        --arch vit_small --data_path /path/to/imagenet/train --output_dir ./out

    # 旧版等价写法（deprecated，仍可用）
    python -m torch.distributed.launch --nproc_per_node=8 main_dino.py \
        --arch vit_small --data_path /path/to/imagenet/train --output_dir ./out

【2. 单机单卡（裸跑，分布式代码路径自动退化）】
直接运行即可，函数内部会兜底写入 MASTER_ADDR/MASTER_PORT，world_size=1：

    python main_dino.py --arch vit_small --data_path /path/to/imagenet/train --output_dir ./out

【3. 多机多卡（手动指定 dist_url）】
需要显式传 --dist_url tcp://<主节点IP>:<空闲端口>，并在每台机器上
手动指定 --rank / --world_size / --local_rank（因为没有 launcher 注入）。
主节点 IP 用 hostname -I 查看，端口随便挑一个未被占用的（如 29500）：

    # 机器1（主节点，主节点 IP 假设 192.168.1.10）
    python main_dino.py --arch vit_small --data_path /path/to/imagenet/train --output_dir ./out \
        --dist_url tcp://192.168.1.10:29500 --world_size 16 --rank 0 --local_rank 0
    # 机器2
    python main_dino.py --arch vit_small --data_path /path/to/imagenet/train --output_dir ./out \
        --dist_url tcp://192.168.1.10:29500 --world_size 16 --rank 8 --local_rank 0

更省事的多机写法（仍用 torchrun，由它自动注入上述变量）：
    # 主节点
    torchrun --nnodes=2 --node_rank=0 --nproc_per_node=8 \
        --master_addr=192.168.1.10 --master_port=29500 main_dino.py ...
    # 副节点
    torchrun --nnodes=2 --node_rank=1 --nproc_per_node=8 \
        --master_addr=192.168.1.10 --master_port=29500 main_dino.py ...

【4. Slurm 集群（submitit）】
用 run_with_submitit.py 启动，dist_url 由脚本自动生成共享文件 URI，无需手动指定：
    python run_with_submitit.py --nodes 2 --ngpus 8 --arch vit_small \
        --data_path /path/to/imagenet/train --output_dir ./out

============================================================================
关键参数速记
============================================================================
  --nproc_per_node : 单机启动的进程数(=本机 GPU 数)
  --nnodes         : 机器总数（多机时）
  --node_rank      : 当前是第几台机器（0 为主节点）
  --master_addr    : 主节点 IP（torchrun 多机模式，等价于内部 dist_url）
  --master_port    : 主节点端口（torchrun 多机模式）
  --dist_url       : 手动多机时传 tcp://IP:PORT；其余情况用默认 env://
============================================================================
"""


def init_distributed_mode(args):

    # 第一种启动场景——用 python -m torch.distributed.launch（或新版 torchrun）启动
    if "RANK" in os.environ and "WORLD_SIZE" in os.environ:
        args.rank = int(os.environ["RANK"])  # !当前进程在全局所有进程中的编号
        args.world_size = int(os.environ["WORLD_SIZE"])  # !总进程数（= 总 GPU 数）
        args.gpu = int(
            os.environ["LOCAL_RANK"]
        )  #!当前进程对应的本机 GPU 编号（LOCAL_RANK）
    # 第二种场景——多机多卡（Slurm 集群 + submitit)
    elif "SLURM_PROCID" in os.environ:
        args.rank = int(
            os.environ["SLURM_PROCID"]
        )  # 利用 Slurm 注入的 SLURM_PROCID 作为全局 rank
        args.gpu = (
            args.rank % torch.cuda.device_count()
        )  # 本机 GPU 编号用 rank % 本机GPU数 推算（跨节点 rank 连续，取模即得到本地设备号）

    # 第三种场景——直接 python main_dino.py 单卡运行（无分布式环境变量，但有 GPU）：
    elif torch.cuda.is_available():
        print("Will run the code on one GPU.")
        # 手动设 rank=0, gpu=0, world_size=1（退化成单进程）
        args.rank, args.gpu, args.world_size = 0, 0, 1
        # 补上 MASTER_ADDR/MASTER_PORT进行兜底，因为后面要初始化进程组init_process_group,保证代码统一
        os.environ["MASTER_ADDR"] = "127.0.0.1"
        os.environ["MASTER_PORT"] = "29500"
    else:
        print("Does not support training without GPU.")
        sys.exit(1)

    # !1.初始化进程组
    dist.init_process_group(
        backend="nccl",  # GPU之间的通信方式
        init_method=args.dist_url,  # dist_url 默认是 env://，地址由启动器torch.distributed.launch自动注入。只有手搓多机训练时才需自己构造
        world_size=args.world_size,  # 总进程数，把所有进程拉到一个组里
        rank=args.rank,  # 当前进程
    )

    # !2.把当前进程绑定到对应的那块 GPU，后续 .cuda() 默认落到该设备。
    torch.cuda.set_device(args.gpu)
    dist.barrier()  # 阻塞直到所有进程都到达这里，保证后续操作（如建模型、读数据）各进程步调一致，避免某些进程提前执行导致通信死锁
    setup_for_distributed(args.rank == 0)


""" 
# 训练的batch数据如下
# images = [
#     tensor[B, 3, 224, 224],   # global crop 1
#     tensor[B, 3, 224, 224],   # global crop 2
#     tensor[B, 3, 96, 96],     # local crop 1
#     ... ×8
# ]

teacher网络只看前两个 global crop: teacher 是「目标网络」，要提供稳定可靠的监督信号，global crop 信息量足够，且避免小图带来的噪声
student网络训练全部 10 个 crop：student 是「学生网络」，要尽可能学到更多细节，local crop 信息量更大，且避免大图带来的信息过载

MultiCropWrapper的作用是：
1. 将backbone的fc和head去掉
2. 将同分辨率批量过 backbone 一次，student网络有两个分辨率，分别喂给backbone
"""


class MultiCropWrapper(nn.Module):
    def __init__(self, backbone, head):
        super().__init__()
        backbone.fc, backbone.head = nn.Identity(), nn.Identity()
        self.backbone = backbone
        self.head = head

    def forward(self, x):
        if not isinstance(x, list):
            x = [x]
        # tensor([224, 224,  96,  96,  96,  96,  96,  96,  96,  96])
        sizes = torch.tensor([inp.shape[-1] for inp in x])

        # unique_consecutive去重，去掉相邻连续重复 返回（[224, 96], [2, 8]）
        counts = torch.unique_consecutive(
            sizes,
            return_counts=True,  # 表示返回计数
        )[
            1
        ]  # [2, 8]

        # 对计数进行累加 [2, 10]
        idx_crops = torch.cumsum(counts, dim=0)

        # print(idx_crops)
        # output = [0]
        start_idx, output = 0, torch.empty(0).to(x[0].device)
        for end_idx in idx_crops:
            # print(f"Processing crops from {start_idx} to {end_idx}")
            """
            将相同尺寸的crop合并并输入到backbone
            global crop = [2*B, 3, 224, 224]
            local crop= [8*B, 3, 96, 96]
            """
            inputs = torch.cat(x[start_idx:end_idx])
            out = self.backbone(inputs)  # out.shape =  (2*B, 768) 或者 (8*B, 768)
            # print(output.shape)
            # print(out.shape)
            # 合并global crop和local crop的结果 (2*B + 8*B, 768) -> (10 * B, 768)
            output = torch.cat((output, out))
            # print(output.shape)
            start_idx = end_idx
        return self.head(output)
